services:
  pg:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=alacena
      - POSTGRES_PASSWORD=87654321
      - POSTGRES_DB=recetas_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: postgresql-alacena
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-alacena
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build: .
    container_name: spring-alacena
    ports:
      - "8081:8080"
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-alacena:5432/recetas_db
      - SPRING_DATASOURCE_USERNAME=alacena
      - SPRING_DATASOURCE_PASSWORD=87654321
    volumes:
      - ./:/app

volumes:
  pgdata:
  pgadmin-data: